import { StyleSheet } from "react-native";

export const palette = {
    primary: "#212121",
    secondary: "#8c8c8c",
    border: "#e4e4e4",
    danger: "#ea4040",
    success: "#178a52",
    surface: "#ffffff",
    soft: "#f6f6f6",
};

export const styles = StyleSheet.create({
    root: {
        flex: 1,
        backgroundColor: palette.surface,
    },
    content: {
        paddingHorizontal: 16,
        paddingBottom: 132,
        gap: 18,
    },
    header: {
        minHeight: 54,
        flexDirection: "row",
        alignItems: "center",
        justifyContent: "space-between",
    },
    iconButton: {
        width: 42,
        height: 42,
        borderRadius: 21,
        borderWidth: 1,
        borderColor: palette.border,
        alignItems: "center",
        justifyContent: "center",
        backgroundColor: palette.surface,
    },
    headerSpacer: {
        width: 42,
        height: 42,
    },
    headerTitle: {
        color: palette.primary,
        fontSize: 18,
        lineHeight: 24,
        fontWeight: "800",
    },
    section: {
        gap: 12,
    },
    sectionTitle: {
        color: palette.primary,
        fontSize: 18,
        lineHeight: 24,
        fontWeight: "800",
    },
    field: {
        gap: 7,
    },
    label: {
        color: palette.primary,
        fontSize: 13,
        lineHeight: 17,
        fontWeight: "800",
    },
    input: {
        minHeight: 48,
        borderWidth: 1,
        borderColor: palette.border,
        borderRadius: 8,
        paddingHorizontal: 14,
        color: palette.primary,
        fontSize: 15,
        lineHeight: 20,
        backgroundColor: palette.surface,
    },
    multilineInput: {
        minHeight: 92,
        paddingTop: 12,
        textAlignVertical: "top",
    },
    errorText: {
        color: palette.danger,
        fontSize: 13,
        lineHeight: 18,
        fontWeight: "600",
    },
    orderPreview: {
        gap: 10,
        borderRadius: 8,
        borderWidth: 1,
        borderColor: palette.border,
        padding: 14,
        backgroundColor: palette.soft,
    },
    previewRow: {
        flexDirection: "row",
        alignItems: "center",
        justifyContent: "space-between",
        gap: 12,
    },
    previewLabel: {
        color: palette.secondary,
        fontSize: 14,
        lineHeight: 18,
        fontWeight: "700",
    },
    previewValue: {
        color: palette.primary,
        fontSize: 15,
        lineHeight: 20,
        fontWeight: "900",
    },
    successWrap: {
        flex: 1,
        minHeight: 520,
        alignItems: "center",
        justifyContent: "center",
        gap: 14,
        paddingHorizontal: 18,
    },
    successIcon: {
        width: 78,
        height: 78,
        borderRadius: 39,
        alignItems: "center",
        justifyContent: "center",
        backgroundColor: "#eaf8f1",
    },
    emptyIcon: {
        width: 78,
        height: 78,
        borderRadius: 39,
        alignItems: "center",
        justifyContent: "center",
        backgroundColor: palette.soft,
    },
    successTitle: {
        color: palette.primary,
        fontSize: 21,
        lineHeight: 27,
        fontWeight: "900",
        textAlign: "center",
    },
    successText: {
        color: palette.secondary,
        fontSize: 14,
        lineHeight: 20,
        fontWeight: "600",
        textAlign: "center",
    },
    bottomBar: {
        position: "absolute",
        left: 0,
        right: 0,
        bottom: 0,
        gap: 12,
        paddingHorizontal: 16,
        paddingTop: 14,
        paddingBottom: 28,
        borderTopWidth: 1,
        borderTopColor: palette.border,
        backgroundColor: palette.surface,
    },
    totalRow: {
        flexDirection: "row",
        alignItems: "center",
        justifyContent: "space-between",
    },
    totalLabel: {
        color: palette.secondary,
        fontSize: 14,
        lineHeight: 18,
        fontWeight: "700",
    },
    totalPrice: {
        color: palette.primary,
        fontSize: 22,
        lineHeight: 28,
        fontWeight: "900",
    },
    submitButton: {
        height: 52,
        borderRadius: 8,
        alignItems: "center",
        justifyContent: "center",
        backgroundColor: palette.primary,
    },
    submitButtonDisabled: {
        opacity: 0.58,
    },
    submitButtonText: {
        color: palette.surface,
        paddingHorizontal: 16,
        fontSize: 16,
        lineHeight: 20,
        fontWeight: "800",
    },
});
