import { StyleSheet } from "react-native";

export const palette = {
    primary: "#212121",
    secondary: "#8c8c8c",
    border: "#e4e4e4",
    sale: "#ea4040",
    surface: "#ffffff",
    soft: "#f6f6f6",
};

export const styles = StyleSheet.create({
    root: {
        flex: 1,
        backgroundColor: palette.surface,
    },
  content: {
    paddingHorizontal: 16,
    paddingBottom: 104,
    gap: 14,
  },
    header: {
        minHeight: 54,
        flexDirection: "row",
        alignItems: "center",
        justifyContent: "space-between",
    },
    iconButton: {
        width: 42,
        height: 42,
        borderRadius: 21,
        borderWidth: 1,
        borderColor: palette.border,
        alignItems: "center",
        justifyContent: "center",
        backgroundColor: palette.surface,
    },
    headerSpacer: {
        width: 42,
        height: 42,
    },
    headerTitle: {
        color: palette.primary,
        fontSize: 18,
        lineHeight: 24,
        fontWeight: "800",
    },
    emptyWrap: {
        flex: 1,
        minHeight: 520,
        alignItems: "center",
        justifyContent: "center",
        gap: 14,
        paddingHorizontal: 18,
    },
    emptyIcon: {
        width: 78,
        height: 78,
        borderRadius: 39,
        alignItems: "center",
        justifyContent: "center",
        backgroundColor: palette.soft,
    },
    emptyTitle: {
        color: palette.primary,
        fontSize: 21,
        lineHeight: 27,
        fontWeight: "900",
        textAlign: "center",
    },
    emptyText: {
        color: palette.secondary,
        fontSize: 14,
        lineHeight: 20,
        fontWeight: "600",
        textAlign: "center",
    },
    continueButton: {
        height: 48,
        borderRadius: 8,
        paddingHorizontal: 22,
        alignItems: "center",
        justifyContent: "center",
        backgroundColor: palette.primary,
    },
    continueButtonText: {
        color: palette.surface,
        fontSize: 15,
        lineHeight: 20,
        fontWeight: "800",
    },
    item: {
        flexDirection: "row",
        gap: 12,
        paddingVertical: 12,
        borderBottomWidth: 1,
        borderBottomColor: palette.border,
    },
    imageWrap: {
        width: 88,
        height: 88,
        borderRadius: 8,
        backgroundColor: palette.soft,
        alignItems: "center",
        justifyContent: "center",
        overflow: "hidden",
    },
    image: {
        width: "86%",
        height: "86%",
    },
    body: {
        flex: 1,
        gap: 6,
    },
    topRow: {
        flexDirection: "row",
        gap: 8,
        alignItems: "flex-start",
    },
    title: {
        flex: 1,
        color: palette.primary,
        fontSize: 15,
        lineHeight: 20,
        fontWeight: "800",
    },
    category: {
        color: palette.secondary,
        fontSize: 12,
        lineHeight: 16,
        fontWeight: "600",
    },
    bottomRow: {
        marginTop: 8,
        flexDirection: "row",
        alignItems: "center",
        justifyContent: "space-between",
        gap: 10,
    },
    price: {
        color: palette.primary,
        fontSize: 16,
        lineHeight: 21,
        fontWeight: "900",
    },
    addButton: {
        minHeight: 38,
        borderRadius: 8,
        paddingHorizontal: 14,
        alignItems: "center",
        justifyContent: "center",
        backgroundColor: palette.primary,
    },
    addButtonText: {
        color: palette.surface,
        fontSize: 13,
        lineHeight: 17,
        fontWeight: "800",
    },
});
