import { StyleSheet } from "react-native";

export const palette = {
    primary: "#212121",
    secondary: "#aeaeae",
    border: "#e4e4e4",
    mutedBorder: "#dbdbdb",
    accent: "#5b24c9",
    sale: "#ea4040",
    surface: "#ffffff",
    soft: "#f6f6f6",
};

export const styles = StyleSheet.create({
    root: {
        flex: 1,
    },
    safeArea: {
        flex: 1,
    },
    content: {
        paddingHorizontal: 16,
        paddingBottom: 108,
        gap: 20,
    },
    header: {
        minHeight: 64,
        flexDirection: "row",
        alignItems: "center",
        justifyContent: "space-between",
        paddingTop: 6,
    },
    logoBlock: {
        gap: 4,
    },
    logoImage: {
        width: 142,
        height: 54,
    },
    tagline: {
        color: palette.secondary,
        fontSize: 13,
        lineHeight: 18,
        fontWeight: "400",
        marginTop: 2,
    },
    headerActions: {
        flexDirection: "row",
        alignItems: "center",
        gap: 8,
    },
    basketButton: {
        width: 44,
        height: 44,
        borderRadius: 22,
        borderWidth: 1,
        borderColor: palette.border,
        alignItems: "center",
        justifyContent: "center",
        backgroundColor: palette.surface,
    },
    languageButton: {
        minWidth: 48,
        height: 44,
        borderRadius: 22,
        borderWidth: 1,
        borderColor: palette.border,
        alignItems: "center",
        justifyContent: "center",
        paddingHorizontal: 10,
        backgroundColor: palette.surface,
    },
    languageButtonText: {
        color: palette.primary,
        fontSize: 13,
        lineHeight: 17,
        fontWeight: "900",
    },
    basketBadge: {
        position: "absolute",
        right: -2,
        top: -4,
        minWidth: 18,
        height: 18,
        borderRadius: 9,
        paddingHorizontal: 4,
        alignItems: "center",
        justifyContent: "center",
        backgroundColor: palette.sale,
    },
    basketBadgeText: {
        color: palette.surface,
        fontSize: 10,
        lineHeight: 12,
        fontWeight: "800",
    },
    stickyPanel: {
        gap: 12,
        paddingTop: 8,
        paddingBottom: 12,
        backgroundColor: palette.surface,
        borderBottomWidth: 1,
        borderBottomColor: "#f1f1f1",
        zIndex: 20,
    },
    searchWrap: {
        height: 48,
        borderWidth: 1,
        borderColor: palette.mutedBorder,
        borderRadius: 8,
        justifyContent: "center",
        backgroundColor: palette.surface,
    },
    searchInput: {
        color: palette.primary,
        fontSize: 15,
        lineHeight: 20,
        paddingLeft: 16,
        paddingRight: 84,
    },
    searchClear: {
        position: "absolute",
        right: 44,
        width: 34,
        height: 34,
        borderRadius: 17,
        alignItems: "center",
        justifyContent: "center",
    },
    searchSubmit: {
        position: "absolute",
        right: 7,
        width: 34,
        height: 34,
        borderRadius: 17,
        alignItems: "center",
        justifyContent: "center",
        backgroundColor: palette.primary,
    },
    searchSuggestions: {
        gap: 2,
        borderRadius: 8,
        borderWidth: 1,
        borderColor: palette.border,
        padding: 6,
        backgroundColor: palette.surface,
        shadowColor: "#000",
        shadowOpacity: 0.08,
        shadowRadius: 10,
        shadowOffset: { width: 0, height: 4 },
        elevation: 4,
    },
    searchSuggestionLoading: {
        minHeight: 54,
        alignItems: "center",
        justifyContent: "center",
    },
    searchSuggestionItem: {
        minHeight: 62,
        flexDirection: "row",
        alignItems: "center",
        gap: 10,
        borderRadius: 7,
        paddingHorizontal: 8,
        paddingVertical: 7,
        backgroundColor: palette.surface,
    },
    searchSuggestionImageWrap: {
        width: 46,
        height: 46,
        borderRadius: 7,
        alignItems: "center",
        justifyContent: "center",
        backgroundColor: palette.soft,
        overflow: "hidden",
    },
    searchSuggestionImage: {
        width: "88%",
        height: "88%",
    },
    searchSuggestionText: {
        flex: 1,
        minWidth: 0,
    },
    searchSuggestionTitle: {
        color: palette.primary,
        fontSize: 14,
        lineHeight: 18,
        fontWeight: "700",
    },
    searchSuggestionMeta: {
        color: palette.secondary,
        fontSize: 12,
        lineHeight: 16,
        fontWeight: "500",
        marginTop: 2,
    },
    searchSuggestionPrice: {
        color: palette.primary,
        fontSize: 13,
        lineHeight: 17,
        fontWeight: "800",
    },
    searchSuggestionAll: {
        minHeight: 42,
        borderRadius: 7,
        alignItems: "center",
        justifyContent: "center",
        backgroundColor: palette.primary,
        marginTop: 4,
    },
    searchSuggestionAllText: {
        color: palette.surface,
        fontSize: 13,
        lineHeight: 17,
        fontWeight: "800",
    },
    brandsButton: {
        minHeight: 42,
        borderRadius: 8,
        borderWidth: 1,
        borderColor: palette.primary,
        alignItems: "center",
        justifyContent: "center",
        backgroundColor: palette.primary,
    },
    brandsButtonText: {
        color: palette.surface,
        fontSize: 14,
        lineHeight: 18,
        fontWeight: "800",
    },
    brandsScreen: {
        flex: 1,
        backgroundColor: palette.surface,
    },
    brandsList: {
        flex: 1,
    },
    brandsPanel: {
        gap: 18,
        paddingHorizontal: 16,
        paddingTop: 8,
        paddingBottom: 108,
    },
    brandsHeader: {
        minHeight: 48,
        flexDirection: "row",
        alignItems: "center",
        gap: 12,
    },
    brandsFixedHeader: {
        flexShrink: 0,
        paddingHorizontal: 16,
        paddingVertical: 8,
        borderBottomWidth: 1,
        borderBottomColor: palette.border,
        backgroundColor: palette.surface,
        zIndex: 2,
    },
    brandsBack: {
        width: 42,
        height: 42,
        borderRadius: 21,
        borderWidth: 1,
        borderColor: palette.border,
        alignItems: "center",
        justifyContent: "center",
        backgroundColor: palette.surface,
    },
    brandsTitle: {
        color: palette.primary,
        fontSize: 24,
        lineHeight: 30,
        fontWeight: "900",
    },
    brandGroup: {
        gap: 8,
    },
    brandLetter: {
        color: palette.secondary,
        fontSize: 13,
        lineHeight: 17,
        fontWeight: "900",
        textTransform: "uppercase",
    },
    brandList: {
        borderRadius: 8,
        borderWidth: 1,
        borderColor: palette.border,
        overflow: "hidden",
        backgroundColor: palette.surface,
    },
    brandItem: {
        minHeight: 46,
        justifyContent: "center",
        borderBottomWidth: 1,
        borderBottomColor: "#f1f1f1",
        paddingHorizontal: 14,
    },
    brandName: {
        color: palette.primary,
        fontSize: 15,
        lineHeight: 20,
        fontWeight: "700",
    },
    categoryList: {
        gap: 10,
        paddingRight: 16,
    },
    categoryIntro: {
        minHeight: 40,
        justifyContent: "center",
        paddingRight: 2,
    },
    categoryIntroLabel: {
        color: palette.secondary,
        fontSize: 12,
        lineHeight: 16,
        fontWeight: "700",
        textTransform: "uppercase",
    },
    categoryChip: {
        minHeight: 40,
        paddingHorizontal: 15,
        borderRadius: 20,
        borderWidth: 1,
        borderColor: palette.border,
        alignItems: "center",
        justifyContent: "center",
        backgroundColor: palette.surface,
    },
    categoryChipActive: {
        borderColor: palette.primary,
        backgroundColor: palette.primary,
    },
    categoryText: {
        color: palette.primary,
        fontSize: 14,
        lineHeight: 18,
        fontWeight: "600",
    },
    categoryTextActive: {
        color: palette.surface,
    },
    subcategoryPanel: {
        gap: 8,
        borderLeftWidth: 2,
        borderLeftColor: palette.primary,
        paddingLeft: 10,
    },
    subcategoryTitle: {
        color: palette.secondary,
        fontSize: 12,
        lineHeight: 16,
        fontWeight: "700",
        textTransform: "uppercase",
    },
    subcategoryList: {
        gap: 8,
        paddingRight: 16,
    },
    subcategoryChip: {
        minHeight: 36,
        paddingHorizontal: 13,
        borderRadius: 8,
        borderWidth: 1,
        borderColor: palette.border,
        alignItems: "center",
        justifyContent: "center",
        backgroundColor: palette.soft,
    },
    subcategoryChipActive: {
        borderColor: palette.accent,
        backgroundColor: "#f3efff",
    },
    subcategoryText: {
        color: palette.primary,
        fontSize: 13,
        lineHeight: 17,
        fontWeight: "600",
    },
    subcategoryTextActive: {
        color: palette.accent,
    },
    activeResults: {
        gap: 12,
        paddingTop: 2,
        paddingBottom: 4,
    },
    brandFiltersPanel: {
        gap: 12,
        borderRadius: 8,
        borderWidth: 1,
        borderColor: palette.border,
        padding: 12,
        backgroundColor: palette.soft,
    },
    brandFiltersHeader: {
        minHeight: 24,
        flexDirection: "row",
        alignItems: "center",
        justifyContent: "space-between",
        gap: 12,
    },
    brandFiltersTitle: {
        color: palette.primary,
        fontSize: 16,
        lineHeight: 21,
        fontWeight: "900",
    },
    brandResetText: {
        color: palette.secondary,
        fontSize: 13,
        lineHeight: 18,
        fontWeight: "800",
    },
    brandSortList: {
        gap: 8,
        paddingRight: 12,
    },
    brandSortChip: {
        minHeight: 36,
        borderRadius: 18,
        borderWidth: 1,
        borderColor: palette.border,
        paddingHorizontal: 13,
        alignItems: "center",
        justifyContent: "center",
        backgroundColor: palette.surface,
    },
    brandSortChipActive: {
        borderColor: palette.primary,
        backgroundColor: palette.primary,
    },
    brandSortText: {
        color: palette.primary,
        fontSize: 13,
        lineHeight: 17,
        fontWeight: "800",
    },
    brandSortTextActive: {
        color: palette.surface,
    },
    brandPriceFilterRow: {
        flexDirection: "row",
        alignItems: "center",
        gap: 8,
        flexWrap: "wrap",
    },
    brandPriceInput: {
        flex: 1,
        minWidth: 118,
        height: 42,
        borderRadius: 8,
        borderWidth: 1,
        borderColor: palette.border,
        paddingHorizontal: 11,
        color: palette.primary,
        fontSize: 14,
        lineHeight: 18,
        fontWeight: "700",
        backgroundColor: palette.surface,
    },
    brandDiscountChip: {
        height: 42,
        borderRadius: 8,
        borderWidth: 1,
        borderColor: palette.border,
        paddingHorizontal: 12,
        alignItems: "center",
        justifyContent: "center",
        backgroundColor: palette.surface,
    },
    brandDiscountChipActive: {
        borderColor: palette.primary,
        backgroundColor: palette.primary,
    },
    brandDiscountText: {
        color: palette.primary,
        fontSize: 13,
        lineHeight: 17,
        fontWeight: "800",
    },
    brandDiscountTextActive: {
        color: palette.surface,
    },
    whatsNew: {
        flexDirection: "row",
        alignItems: "center",
        justifyContent: "space-between",
        gap: 12,
        borderWidth: 1,
        borderColor: palette.border,
        borderRadius: 8,
        padding: 14,
        backgroundColor: palette.soft,
    },
    whatsNewText: {
        flex: 1,
    },
    whatsNewLabel: {
        color: palette.accent,
        fontSize: 13,
        lineHeight: 18,
        fontWeight: "700",
        textTransform: "uppercase",
    },
    whatsNewBody: {
        color: palette.primary,
        fontSize: 15,
        lineHeight: 21,
        fontWeight: "500",
        marginTop: 4,
    },
    whatsNewButton: {
        minHeight: 40,
        paddingHorizontal: 14,
        borderRadius: 6,
        alignItems: "center",
        justifyContent: "center",
        backgroundColor: palette.primary,
    },
    whatsNewButtonDisabled: {
        opacity: 0.45,
    },
    whatsNewButtonText: {
        color: palette.surface,
        fontSize: 13,
        lineHeight: 16,
        fontWeight: "600",
    },
    loadingCard: {
        minHeight: 92,
        gap: 10,
        alignItems: "center",
        justifyContent: "center",
        borderRadius: 8,
        borderWidth: 1,
        borderColor: palette.border,
        backgroundColor: palette.soft,
    },
    loadingText: {
        color: palette.secondary,
        fontSize: 14,
        lineHeight: 20,
        fontWeight: "500",
    },
    errorCard: {
        minHeight: 92,
        justifyContent: "center",
        borderRadius: 8,
        borderWidth: 1,
        borderColor: palette.sale,
        padding: 16,
        backgroundColor: "#fff5f5",
    },
    errorTitle: {
        color: palette.sale,
        fontSize: 15,
        lineHeight: 21,
        fontWeight: "700",
    },
    errorText: {
        color: palette.primary,
        fontSize: 13,
        lineHeight: 18,
        fontWeight: "500",
        marginTop: 4,
    },
    heroList: {
        gap: 12,
        paddingRight: 16,
    },
    heroCard: {
        width: 312,
        height: 164,
        overflow: "hidden",
        borderRadius: 8,
        backgroundColor: palette.soft,
    },
    heroCardDisabled: {
        opacity: 1,
    },
    absoluteFill: {
        ...StyleSheet.absoluteFill,
    },
    heroOverlay: {
        ...StyleSheet.absoluteFill,
        backgroundColor: "rgba(0,0,0,0.22)",
    },
    heroCopy: {
        position: "absolute",
        left: 18,
        right: 18,
        bottom: 18,
    },
    heroTitle: {
        color: palette.surface,
        fontSize: 25,
        lineHeight: 30,
        fontWeight: "700",
        textShadowColor: "rgba(0,0,0,0.28)",
        textShadowOffset: { width: 0, height: 1 },
        textShadowRadius: 3,
    },
    heroSubtitle: {
        color: palette.surface,
        fontSize: 14,
        lineHeight: 20,
        fontWeight: "500",
        marginTop: 4,
        textShadowColor: "rgba(0,0,0,0.22)",
        textShadowOffset: { width: 0, height: 1 },
        textShadowRadius: 2,
    },
    section: {
        gap: 12,
        paddingTop: 2,
    },
    sectionHeader: {
        minHeight: 36,
        flexDirection: "row",
        alignItems: "center",
        justifyContent: "space-between",
    },
    sectionTitle: {
        color: palette.primary,
        fontSize: 22,
        lineHeight: 28,
        fontWeight: "700",
    },
    sectionActionButton: {
        minHeight: 32,
        borderRadius: 16,
        paddingHorizontal: 12,
        alignItems: "center",
        justifyContent: "center",
        backgroundColor: palette.soft,
        borderWidth: 1,
        borderColor: palette.border,
    },
    sectionAction: {
        color: palette.secondary,
        fontSize: 14,
        lineHeight: 20,
        fontWeight: "600",
    },
    inlineLoader: {
        minHeight: 120,
        alignItems: "center",
        justifyContent: "center",
    },
    feedStatus: {
        minHeight: 64,
        gap: 8,
        alignItems: "center",
        justifyContent: "center",
        paddingVertical: 12,
    },
    feedStatusText: {
        color: palette.secondary,
        fontSize: 13,
        lineHeight: 18,
        fontWeight: "500",
        textAlign: "center",
    },
    productGrid: {
        flexDirection: "row",
        flexWrap: "wrap",
        justifyContent: "space-between",
        rowGap: 20,
    },
    emptyText: {
        color: palette.secondary,
        fontSize: 14,
        lineHeight: 20,
        fontWeight: "500",
    },
    productCard: {
        width: "47.8%",
        flexBasis: "47.8%",
        maxWidth: "47.8%",
        minWidth: 0,
        minHeight: 300,
    },
    productImageWrap: {
        width: "100%",
        aspectRatio: 4 / 5,
        alignItems: "center",
        justifyContent: "center",
        backgroundColor: palette.soft,
        borderRadius: 8,
        overflow: "hidden",
    },
    productCardFavoriteIcon: {
        position: "absolute",
        left: 8,
        top: 8,
        width: 34,
        height: 34,
        borderRadius: 17,
        borderWidth: 1,
        borderColor: palette.border,
        alignItems: "center",
        justifyContent: "center",
        backgroundColor: palette.surface,
    },
    productImage: {
        width: "88%",
        height: "88%",
    },
    imageFallback: {
        color: palette.secondary,
        fontSize: 13,
        lineHeight: 18,
        fontWeight: "500",
    },
    productTitle: {
        color: palette.primary,
        fontSize: 14,
        lineHeight: 20,
        fontWeight: "600",
        marginTop: 12,
        minHeight: 40,
    },
    productCategory: {
        color: palette.secondary,
        fontSize: 13,
        lineHeight: 18,
        fontWeight: "400",
        marginTop: 4,
    },
    priceRow: {
        minHeight: 25,
        flexDirection: "row",
        alignItems: "baseline",
        gap: 8,
        marginTop: 10,
        flexWrap: "wrap",
    },
    price: {
        color: palette.primary,
        fontSize: 16,
        lineHeight: 22,
        fontWeight: "700",
    },
    salePrice: {
        color: palette.sale,
    },
    oldPrice: {
        color: palette.secondary,
        fontSize: 12,
        lineHeight: 16,
        fontWeight: "500",
        textDecorationLine: "line-through",
    },
    cartButton: {
        height: 42,
        alignItems: "center",
        justifyContent: "center",
        borderRadius: 6,
        backgroundColor: palette.primary,
        marginTop: 12,
    },
    cartButtonText: {
        color: palette.surface,
        fontSize: 14,
        lineHeight: 18,
        fontWeight: "600",
    },
});
