import { StyleSheet } from "react-native";

export const palette = {
    primary: "#212121",
    secondary: "#8c8c8c",
    border: "#e4e4e4",
    surface: "#ffffff",
    soft: "#f6f6f6",
};

export const styles = StyleSheet.create({
    root: {
        flex: 1,
        backgroundColor: palette.surface,
    },
  content: {
    paddingHorizontal: 16,
    paddingBottom: 104,
    gap: 18,
  },
    header: {
        minHeight: 58,
        justifyContent: "center",
    },
    title: {
        color: palette.primary,
        fontSize: 25,
        lineHeight: 31,
        fontWeight: "900",
    },
    subtitle: {
        color: palette.secondary,
        fontSize: 14,
        lineHeight: 20,
        fontWeight: "600",
        marginTop: 4,
    },
    parentList: {
        gap: 10,
        paddingRight: 16,
    },
    parentChip: {
        minHeight: 42,
        borderRadius: 21,
        borderWidth: 1,
        borderColor: palette.border,
        paddingHorizontal: 16,
        alignItems: "center",
        justifyContent: "center",
        backgroundColor: palette.surface,
    },
    parentChipActive: {
        borderColor: palette.primary,
        backgroundColor: palette.primary,
    },
    parentText: {
        color: palette.primary,
        fontSize: 14,
        lineHeight: 18,
        fontWeight: "800",
    },
    parentTextActive: {
        color: palette.surface,
    },
    subcategoryPanel: {
        gap: 10,
        borderLeftWidth: 2,
        borderLeftColor: palette.primary,
        paddingLeft: 10,
    },
    subcategoryTitle: {
        color: palette.secondary,
        fontSize: 12,
        lineHeight: 16,
        fontWeight: "800",
        textTransform: "uppercase",
    },
    subcategoryList: {
        gap: 8,
        paddingRight: 16,
    },
    subcategoryChip: {
        minHeight: 36,
        borderRadius: 8,
        borderWidth: 1,
        borderColor: palette.border,
        paddingHorizontal: 13,
        alignItems: "center",
        justifyContent: "center",
        backgroundColor: palette.soft,
    },
    subcategoryChipActive: {
        borderColor: palette.primary,
        backgroundColor: palette.surface,
    },
    subcategoryText: {
        color: palette.primary,
        fontSize: 13,
        lineHeight: 17,
        fontWeight: "700",
    },
    filtersPanel: {
        gap: 12,
        borderRadius: 8,
        borderWidth: 1,
        borderColor: palette.border,
        padding: 12,
        backgroundColor: palette.soft,
    },
    filtersHeader: {
        minHeight: 24,
        flexDirection: "row",
        alignItems: "center",
        justifyContent: "space-between",
        gap: 12,
    },
    filtersTitle: {
        color: palette.primary,
        fontSize: 16,
        lineHeight: 21,
        fontWeight: "900",
    },
    resetText: {
        color: palette.secondary,
        fontSize: 13,
        lineHeight: 18,
        fontWeight: "800",
    },
    sortList: {
        gap: 8,
        paddingRight: 12,
    },
    sortChip: {
        minHeight: 36,
        borderRadius: 18,
        borderWidth: 1,
        borderColor: palette.border,
        paddingHorizontal: 13,
        alignItems: "center",
        justifyContent: "center",
        backgroundColor: palette.surface,
    },
    sortChipActive: {
        borderColor: palette.primary,
        backgroundColor: palette.primary,
    },
    sortText: {
        color: palette.primary,
        fontSize: 13,
        lineHeight: 17,
        fontWeight: "800",
    },
    sortTextActive: {
        color: palette.surface,
    },
    priceFilterRow: {
        flexDirection: "row",
        alignItems: "center",
        gap: 8,
    },
    priceInput: {
        flex: 1,
        height: 42,
        borderRadius: 8,
        borderWidth: 1,
        borderColor: palette.border,
        paddingHorizontal: 11,
        color: palette.primary,
        fontSize: 14,
        lineHeight: 18,
        fontWeight: "700",
        backgroundColor: palette.surface,
    },
    discountChip: {
        height: 42,
        borderRadius: 8,
        borderWidth: 1,
        borderColor: palette.border,
        paddingHorizontal: 12,
        alignItems: "center",
        justifyContent: "center",
        backgroundColor: palette.surface,
    },
    discountChipActive: {
        borderColor: palette.primary,
        backgroundColor: palette.primary,
    },
    discountText: {
        color: palette.primary,
        fontSize: 13,
        lineHeight: 17,
        fontWeight: "800",
    },
    discountTextActive: {
        color: palette.surface,
    },
    sectionTitle: {
        color: palette.primary,
		textTransform: "capitalize",
        fontSize: 20,
        lineHeight: 26,
        fontWeight: "900",
    },
    loadingWrap: {
        minHeight: 180,
        alignItems: "center",
        justifyContent: "center",
    },
    emptyText: {
        color: palette.secondary,
        fontSize: 14,
        lineHeight: 20,
        fontWeight: "600",
    },
});
