import { StyleSheet } from "react-native";

export const palette = {
    primary: "#212121",
    secondary: "#8c8c8c",
    border: "#e4e4e4",
    surface: "#ffffff",
    soft: "#f6f6f6",
};

export const styles = StyleSheet.create({
    root: {
        flex: 1,
        backgroundColor: palette.surface,
    },
    content: {
        paddingHorizontal: 16,
        paddingTop: 52,
        paddingBottom: 112,
        gap: 18,
    },
    header: {
        minHeight: 58,
        justifyContent: "center",
    },
    title: {
        color: palette.primary,
        fontSize: 25,
        lineHeight: 31,
        fontWeight: "900",
    },
    subtitle: {
        color: palette.secondary,
        fontSize: 14,
        lineHeight: 20,
        fontWeight: "600",
        marginTop: 4,
    },
    parentList: {
        gap: 10,
        paddingRight: 16,
    },
    parentChip: {
        minHeight: 42,
        borderRadius: 21,
        borderWidth: 1,
        borderColor: palette.border,
        paddingHorizontal: 16,
        alignItems: "center",
        justifyContent: "center",
        backgroundColor: palette.surface,
    },
    parentChipActive: {
        borderColor: palette.primary,
        backgroundColor: palette.primary,
    },
    parentText: {
        color: palette.primary,
        fontSize: 14,
        lineHeight: 18,
        fontWeight: "800",
    },
    parentTextActive: {
        color: palette.surface,
    },
    fixedBackBar: {
        position: "absolute",
        top: 34,
        left: 16,
        right: 16,
        zIndex: 50,
        alignItems: "flex-start",
    },
    categoryPanel: {
        gap: 14,
		marginTop: 20,
    },
    backButton: {
        alignSelf: "flex-start",
        minHeight: 38,
        flexDirection: "row",
        alignItems: "center",
        gap: 8,
        borderRadius: 19,
        borderWidth: 1,
        borderColor: palette.border,
        paddingHorizontal: 12,
        backgroundColor: palette.surface,
    },
    backButtonText: {
        color: palette.primary,
        fontSize: 14,
        lineHeight: 18,
        fontWeight: "800",
    },
    categoryLevelCard: {
        gap: 10,
        borderRadius: 8,
        borderWidth: 1,
        borderColor: palette.border,
        padding: 14,
        backgroundColor: palette.soft,
    },
    categoryTrail: {
        color: palette.secondary,
        fontSize: 12,
        lineHeight: 16,
        fontWeight: "800",
    },
    categoryLevelHeader: {
        minHeight: 48,
        flexDirection: "row",
        alignItems: "center",
        justifyContent: "space-between",
        gap: 12,
    },
    categoryLevelText: {
        flex: 1,
        minWidth: 0,
    },
    categoryLevelTitle: {
        color: palette.primary,
        fontSize: 22,
        lineHeight: 28,
        fontWeight: "900",
        textTransform: "capitalize",
    },
    categoryLevelMeta: {
        color: palette.secondary,
        fontSize: 13,
        lineHeight: 18,
        fontWeight: "700",
        marginTop: 3,
    },
    categoryCountPill: {
        minWidth: 38,
        height: 34,
        borderRadius: 17,
        alignItems: "center",
        justifyContent: "center",
        backgroundColor: palette.primary,
        paddingHorizontal: 10,
    },
    categoryCountText: {
        color: palette.surface,
        fontSize: 13,
        lineHeight: 17,
        fontWeight: "900",
    },
    categoryList: {
        gap: 9,
    },
    categoryRow: {
        minHeight: 62,
        flexDirection: "row",
        alignItems: "center",
        gap: 12,
        borderRadius: 8,
        borderWidth: 1,
        borderColor: palette.border,
        paddingHorizontal: 14,
        paddingVertical: 10,
        backgroundColor: palette.surface,
    },
    categoryRowCopy: {
        flex: 1,
        minWidth: 0,
    },
    categoryRowText: {
        color: palette.primary,
        fontSize: 16,
        lineHeight: 21,
        fontWeight: "900",
        textTransform: "capitalize",
    },
    categoryRowMeta: {
        color: palette.secondary,
        fontSize: 12,
        lineHeight: 16,
        fontWeight: "700",
        marginTop: 2,
    },
    categoryArrow: {
        width: 34,
        height: 34,
        borderRadius: 17,
        alignItems: "center",
        justifyContent: "center",
        backgroundColor: palette.soft,
    },
    noSubcategories: {
        minHeight: 46,
        borderRadius: 8,
        alignItems: "center",
        justifyContent: "center",
        backgroundColor: palette.soft,
        paddingHorizontal: 12,
    },
    noSubcategoriesText: {
        color: palette.secondary,
        fontSize: 13,
        lineHeight: 18,
        fontWeight: "800",
    },
    subcategoryPanel: {
        gap: 10,
        borderLeftWidth: 2,
        borderLeftColor: palette.primary,
        paddingLeft: 10,
    },
    subcategoryTitle: {
        color: palette.secondary,
        fontSize: 12,
        lineHeight: 16,
        fontWeight: "800",
        textTransform: "uppercase",
    },
    subcategoryList: {
        gap: 8,
        paddingRight: 16,
    },
    subcategoryChip: {
        minHeight: 36,
        borderRadius: 8,
        borderWidth: 1,
        borderColor: palette.border,
        paddingHorizontal: 13,
        alignItems: "center",
        justifyContent: "center",
        backgroundColor: palette.soft,
    },
    subcategoryChipActive: {
        borderColor: palette.primary,
        backgroundColor: palette.surface,
    },
    subcategoryText: {
        color: palette.primary,
        fontSize: 13,
        lineHeight: 17,
        fontWeight: "700",
    },
    filtersPanel: {
        gap: 12,
        borderRadius: 8,
        borderWidth: 1,
        borderColor: palette.border,
        padding: 12,
        backgroundColor: palette.soft,
		marginTop: 20,
    },
    filtersHeader: {
        minHeight: 24,
        flexDirection: "row",
        alignItems: "center",
        justifyContent: "space-between",
        gap: 12,
    },
    filtersTitle: {
        color: palette.primary,
        fontSize: 16,
        lineHeight: 21,
        fontWeight: "900",
    },
    resetText: {
        color: palette.secondary,
        fontSize: 13,
        lineHeight: 18,
        fontWeight: "800",
    },
    sortList: {
        gap: 8,
        paddingRight: 12,
    },
    sortChip: {
        minHeight: 36,
        borderRadius: 18,
        borderWidth: 1,
        borderColor: palette.border,
        paddingHorizontal: 13,
        alignItems: "center",
        justifyContent: "center",
        backgroundColor: palette.surface,
    },
    sortChipActive: {
        borderColor: palette.primary,
        backgroundColor: palette.primary,
    },
    sortText: {
        color: palette.primary,
        fontSize: 13,
        lineHeight: 17,
        fontWeight: "800",
    },
    sortTextActive: {
        color: palette.surface,
    },
    priceFilterRow: {
        flexDirection: "row",
        alignItems: "center",
        gap: 8,
        flexWrap: "wrap",
    },
    priceInput: {
        flex: 1,
        minWidth: 118,
        height: 42,
        borderRadius: 8,
        borderWidth: 1,
        borderColor: palette.border,
        paddingHorizontal: 11,
        color: palette.primary,
        fontSize: 14,
        lineHeight: 18,
        fontWeight: "700",
        backgroundColor: palette.surface,
    },
    discountChip: {
        height: 42,
        borderRadius: 8,
        borderWidth: 1,
        borderColor: palette.border,
        paddingHorizontal: 12,
        alignItems: "center",
        justifyContent: "center",
        backgroundColor: palette.surface,
    },
    discountChipActive: {
        borderColor: palette.primary,
        backgroundColor: palette.primary,
    },
    discountText: {
        color: palette.primary,
        fontSize: 13,
        lineHeight: 17,
        fontWeight: "800",
    },
    discountTextActive: {
        color: palette.surface,
    },
    sectionTitle: {
        color: palette.primary,
		textTransform: "capitalize",
        fontSize: 20,
        lineHeight: 26,
        fontWeight: "900",
		marginTop: 20,
    },
    productColumn: {
        justifyContent: "space-between",
        marginBottom: 20,
    },
    productsFooter: {
        paddingBottom: 4,
    },
    loadingWrap: {
        minHeight: 180,
        alignItems: "center",
        justifyContent: "center",
    },
    emptyText: {
        color: palette.secondary,
        fontSize: 14,
        lineHeight: 20,
        fontWeight: "600",
    },
});
