import { StyleSheet } from 'react-native';

export const palette = {
  primary: '#212121',
  secondary: '#8c8c8c',
  border: '#e4e4e4',
  sale: '#ea4040',
  surface: '#ffffff',
  soft: '#f6f6f6',
};

export const styles = StyleSheet.create({
  root: {
    flex: 1,
    backgroundColor: palette.surface,
  },
  content: {
    paddingHorizontal: 16,
    paddingBottom: 188,
    gap: 14,
  },
  header: {
    minHeight: 54,
	paddingHorizontal: 16,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  iconButton: {
    width: 42,
    height: 42,
    borderRadius: 21,
    borderWidth: 1,
    borderColor: palette.border,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: palette.surface,
  },
  headerSpacer: {
    width: 42,
    height: 42,
  },
  headerTitle: {
    color: palette.primary,
    fontSize: 18,
    lineHeight: 24,
    fontWeight: '800',
  },
  clearText: {
    color: palette.secondary,
    fontSize: 13,
    lineHeight: 18,
    fontWeight: '700',
  },
  emptyWrap: {
    flex: 1,
    minHeight: 420,
    alignItems: 'center',
    justifyContent: 'center',
    gap: 14,
  },
  emptyIcon: {
    width: 76,
    height: 76,
    borderRadius: 38,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: palette.soft,
  },
  emptyTitle: {
    color: palette.primary,
    fontSize: 20,
    lineHeight: 26,
    fontWeight: '800',
  },
  emptyText: {
    maxWidth: 260,
    color: palette.secondary,
    fontSize: 14,
    lineHeight: 20,
    fontWeight: '500',
    textAlign: 'center',
  },
  continueButton: {
    height: 48,
    borderRadius: 8,
    paddingHorizontal: 22,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: palette.primary,
  },
  continueButtonText: {
    color: palette.surface,
    fontSize: 15,
    lineHeight: 20,
    fontWeight: '800',
  },
  cartItem: {
    flexDirection: 'row',
    gap: 12,
    paddingVertical: 12,
    borderBottomWidth: 1,
    borderBottomColor: palette.border,
  },
  itemImageWrap: {
    width: 88,
    height: 88,
    borderRadius: 8,
    backgroundColor: palette.soft,
    alignItems: 'center',
    justifyContent: 'center',
    overflow: 'hidden',
  },
  itemImage: {
    width: '86%',
    height: '86%',
  },
  itemBody: {
    flex: 1,
    gap: 6,
  },
  itemTopRow: {
    flexDirection: 'row',
    gap: 8,
    alignItems: 'flex-start',
  },
  itemTitle: {
    flex: 1,
    color: palette.primary,
    fontSize: 15,
    lineHeight: 20,
    fontWeight: '800',
  },
  itemCategory: {
    color: palette.secondary,
    fontSize: 12,
    lineHeight: 16,
    fontWeight: '600',
  },
  itemVariation: {
    alignSelf: 'flex-start',
    borderRadius: 7,
    paddingHorizontal: 8,
    paddingVertical: 4,
    backgroundColor: palette.soft,
  },
  itemVariationText: {
    color: palette.primary,
    fontSize: 12,
    lineHeight: 15,
    fontWeight: '700',
  },
  itemBottomRow: {
    marginTop: 4,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 10,
  },
  itemPrice: {
    color: palette.primary,
    fontSize: 16,
    lineHeight: 21,
    fontWeight: '900',
  },
  quantityControl: {
    flexDirection: 'row',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: palette.border,
    borderRadius: 8,
    overflow: 'hidden',
  },
  quantityButton: {
    width: 34,
    height: 34,
    alignItems: 'center',
    justifyContent: 'center',
  },
  quantityText: {
    minWidth: 32,
    color: palette.primary,
    fontSize: 14,
    lineHeight: 18,
    fontWeight: '800',
    textAlign: 'center',
  },
  bottomBar: {
    position: 'absolute',
    left: 0,
    right: 0,
    bottom: 0,
    gap: 12,
    paddingHorizontal: 16,
    paddingTop: 14,
    paddingBottom: 28,
    borderTopWidth: 1,
    borderTopColor: palette.border,
    backgroundColor: palette.surface,
  },
  totalRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  totalLabel: {
    color: palette.secondary,
    fontSize: 14,
    lineHeight: 18,
    fontWeight: '700',
  },
  totalPrice: {
    color: palette.primary,
    fontSize: 22,
    lineHeight: 28,
    fontWeight: '900',
  },
  checkoutButton: {
    height: 52,
    borderRadius: 8,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: palette.primary,
  },
  checkoutButtonText: {
    color: palette.surface,
    fontSize: 16,
    lineHeight: 20,
    fontWeight: '800',
  },
  continueOutlineButton: {
    height: 48,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: palette.border,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: palette.surface,
  },
  continueOutlineButtonText: {
    color: palette.primary,
    fontSize: 15,
    lineHeight: 20,
    fontWeight: '800',
  },
});
